apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-ansible-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: demo-operator
  template:
    metadata:
      labels:
        name: demo-operator
    spec:
      containers:
        - name: demoapp-ansible-operator
          image: quay.io/shawn_hurley/demoapp-ansible-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
